import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
export default function Cat() {
return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
      <h1>Zen Center: Cats</h1>
        <Image src="/cat_one.jpg" alt="cat"width="200px"height="200px"/>
        <Image src="/cat_two.jpg" alt="cat" width="200px"height="200px"/>
        <Image src="/cat_three.jpg" alt="cat" width="200px"height="200px"/>
        <br/>
        <Link href="/"> 
        <a class="btn btn-success">Home</a>
        </Link>
      </main>
      </div>
)}