import React, { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link';
export default function Contact() {
  const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  const NAME_REGEX = /^[a-zA-Z ]{2,30}$/;
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [emailError, setEmailError] = useState("");
  const [nameError, setNameError] = useState("");

  const validateEmail = (email) => {
    return EMAIL_REGEX.test(String(email).toLowerCase());
  }

  const validateName = (name) => {
    return NAME_REGEX.test(String(name));
  }

  const handleSubmit = (e) => {
    e.preventDefault();

    if (validateEmail(email) && validateName(name)) 
    {
      setEmail("");
      setName("");
      alert("Form submitted successfully");
    }
    else {
      if (!validateEmail(email)) {
        setEmailError("Please enter a valid email address");
      }
      else {
        setEmailError("");
      }
      if (!validateName(name)) {
        setNameError("Please enter a valid name");
      }
      else {
        setNameError("");
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.login}>
        <h1 className={styles.title}>
          Contact Me:
        </h1>
        <div className={styles.grid}>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label htmlFor="name">Full Name</label>
                <input type="text" name="name" id="name" placeholder="" value={name} onChange={(e) => setName(e.target.value)}/>
                {nameError && <span className="error">{nameError}</span>}
                <label htmlFor="email">Email address</label>
                <input type="email" className="form-control" id="email" placeholder="Enter email" value={email} onChange={(e) => setEmail(e.target.value)}/>
                {emailError && <span className="error">{emailError}</span>}
              </div>
              <button type="submit" className="btn btn-primary">Submit</button>
            </form>
        </div>
        <Link href="/">
          <button className="btn btn-success">Home</button>
        </Link>
      </main>
    </div>
  )
}