import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
export default function Flower() {
return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
      <h1>Zen Center: Flowers</h1>
      <Image src="flower_one.jpg" alt="flower"style="width:200px;height:200px;"/>
<Image src="flower_two.jpg" alt="flower" style="width:200px;height:200px;"/>
<Image src="flower_three.jpg" alt="flower"style="width:200px;height:200px;"/>
      </main>
      </div>
)}