import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
export default function Flower() {
return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
      <h1>Zen Center: Flowers</h1>
        <Image
          src="/flower_one.jpg"
          alt="flower"
          width="200px"
          height="200px"
          priority/>
        <Image
          src="/flower_two.jpg"
          alt="flower"
          width="200px"
          height="200px"/>
        <br/>
        <h5>Do you want to visit the cats?</h5>
        <Link href="/Cat"> 
          <a className="btn btn-dark">Cats</a>
          </Link>
        <h5>Do you want to go back to the home page?</h5>
        <Link href="/"> 
        <a className="btn btn-success">Home</a>
        </Link>
      </main>
      </div>
)}