/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
        <h1> Welcome to the Zen Center!</h1>
        <br/>
        <h4>Bio: </h4>
        <Image  alt="A black book in a grey background."src="/bout.jpg" width="200" height="200"/>
        <br/>
        <a href="/About"> About</a>

        <h4> Nature and Enlightenment: </h4>
        <Image  alt="A small purple flower ."src="/flower.jpg" width="200" height="200"/>
        <br/>
        <Image  alt="An animated blue cat."src="/cartooncat.png" width="200" height="200"/>
        <br/>
        <a href="/MenuNature"> Nature Site</a>
        <h4> Quotes: </h4>
        <br/>
        <p> INSERT PHOTO  HERE</p>
        <a href="Quotes"> Quotes</a>
        <h4>Contact Me: </h4>
        <Image  alt="A yellow sticky note saying Call Me."src="/contact.png" width="200" height="200"/> 
        <br/>
        <a href="Contact"> Contact Me</a>
      </main>
    </div>
  )
}