import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zen Station</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.pages}>
        <h1> Welcome to the Zen Station!</h1>
        <div className={styles.spacing}></div>
        <section>
          <header>Bio:</header>
        </section>
        <div className={styles.imageContainer}>
          <Image
            alt="A book about Zen meditation."
            src="/bout.jpg"
            width="200"
            height="200"
            className={styles.image}
            priority/>
        </div>
        <div className={styles.spacing}></div>
        <Link href="/About">
          <button className="btn btn-success">About Me</button>
        </Link>
        <section>
          <header>Nature and Enlightenment:</header>
        </section>
        <p>
          Nature and enlightenment are two of the most important concepts in the world.
          They are the basis of everything we do, and they are the basis of our daily lives.
          They are the basis of our existence.
          </p>
        <Image  alt="A small purple flower." src="/flower.jpg" width="200" height="200"/>
        <div className={styles.spacing}></div>
        <section>
          <header>Quotes:</header>
        </section>
        <Image alt="asdf" src="/quotes.png" width="200" height="200"/>
        <div className={styles.spacing}></div>
        <Link href="/Quotes">
          <button className="btn btn-success">Quotes</button>
        </Link>
        <section>
          <header>Contact Me:</header>
        </section>
        <Image  alt="A yellow sticky note saying Call Me." src="/contact.png" width="200" height="200"/> 
        <div className={styles.spacing}></div>
        <Link href="/Contact">
          <button className="btn btn-success">Contact Me</button>
        </Link>
      </main>
    </div>
  )
}