
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
export default function MenuNature() {
return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
      <h4>Menu Nature</h4>
        <ul>
          <li>
          <Link href="/Flower"> 
          <a>Flowers</a>
          </Link>
          </li>
          <li>
          <Link href="/"> 
          <a>Cats</a>
          </Link>
          </li>
          </ul>
<Link href="/"> 
<a class="btn btn-success">Home</a>
</Link>
</main>
</div>
)}