import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'

const api_url ="https://zenquotes.io/api/random/";
async function getNewQuote(url)
{
  const response = await fetch(url);
  var data = await response.json();
  console.log(data);
  return data;
}

export default function Quotes() 
{
  const [quote, setQuote] = useState("");
  const [author, setAuthor] = useState("");

  useEffect(() => {
    getNewQuote(api_url).then(data => {
      setQuote(data[0].q);
      setAuthor(data[0].a);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pages}>
        <h2> Random Quotes: </h2>
        <div className={styles.container}>
          <h4>
            <p>  &quot; </p>
            <div className="quote">{quote}</div> 
            <p> &quot; </p>
          </h4>
          <h5><p className="author">{author}</p> </h5>     
          <hr/>
        </div>
        <div/>
        <h5>Do you want to go back to the home page?</h5>
        <Link href="/"> 
          <a className="btn btn-success">Home</a>
        </Link>
      </main>
    </div>
  )
}